version: "2"
checks:
  identical-code:
    enabled: false
  similar-code:
    enabled: false
exclude_patterns:
  - "**/node_modules/"
  - "script/"
  - "dist/"
  - "integration_tests/"
  - "mockApis/"
  - "**/*.test.ts"
